server:
  port: 9999
spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/fhzheng/shoe-city.git
          search-paths: config
          default-label: master
          username: 2060992423@qq.com
          password: qwer5271287q
